export const SENTENCES = [
  'The quick brown fox jumps over the lazy dog.',
  'Pack my box with five dozen liquor jugs.',
  'How vexingly quick daft zebras jump.',
  'The five boxing wizards jump quickly.',
  'Sphinx of black quartz judge my vow.',
  'Two driven jocks help fax my big quiz.',
  'Five quacking zephyrs jolt my wax bed.',
  'Crazy Frederick bought many very exquisite opal jewels.',
  'We promptly judged antique ivory buckles for the next prize.',
  'Jaded zombies acted quaintly but kept driving their oxen forward.',
  'The jay, pig, fox, zebra and my wolves quack.',
  'Sympathizing would fix Quaker objectives.',
  'A wizard\'s job is to vex \'chumps\' quickly in fog.',
  'Watch Jeopardy Alex Trebek\'s fun TV quiz game.',
  'When zombies arrive quickly fax Judge Pat.',
  'Waltz bad nymph for quick jigs vex.',
  'Glib jocks quiz nymph to vex dwarf.',
  'Sphinx of black quartz judge my vow.',
  'How quickly daft jumping zebras vex.',
  'Quick zephyrs blow vexing daft Jim.',
  'The lazy dog slept under the warm sun.',
  'Birds fly south for the winter season.',
  'She read the book in one sitting.',
  'The old man walked slowly down the street.',
  'Children play in the park every afternoon.',
  'Coffee tastes better in the morning.',
  'Music fills the room with joy.',
  'Rain fell softly on the roof.',
  'The cat curled up by the fire.',
  'Stars twinkle in the night sky.',
  'Time flies when you are having fun.',
  'Learning new skills takes practice and patience.',
  'The river flows gently through the valley.',
  'Books open doors to new worlds.',
  'Friends make life more enjoyable.',
  'Nature has a way of healing the soul.',
  'Every day brings new opportunities.',
  'Kindness costs nothing but means everything.',
  'The best things in life are free.',
  'Hard work always pays off in the end.',
  'A smile can brighten someone else\'s day.',
  'Change is the only constant in life.',
  'Dreams give us something to strive for.',
  'Patience is a virtue worth cultivating.',
  'The early bird catches the worm.',
  'Actions speak louder than words.',
  'Practice makes perfect over time.',
  'Life is what you make of it.',
  'Every cloud has a silver lining.',
  'The journey of a thousand miles begins with a single step.',
] as const

export function getRandomSentence(): string {
  const idx = Math.floor(Math.random() * SENTENCES.length)
  return SENTENCES[idx]
}
