export const SENTENCES = [
  'The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs. How vexingly quick daft zebras jump. The five boxing wizards jump quickly. Sphinx of black quartz judge my vow. Two driven jocks help fax my big quiz. Five quacking zephyrs jolt my wax bed. Crazy Frederick bought many very exquisite opal jewels. We promptly judged antique ivory buckles for the next prize.',
  'Jaded zombies acted quaintly but kept driving their oxen forward. The jay, pig, fox, zebra and my wolves quack. Sympathizing would fix Quaker objectives. A wizard\'s job is to vex \'chumps\' quickly in fog. Watch Jeopardy Alex Trebek\'s fun TV quiz game. When zombies arrive quickly fax Judge Pat. Waltz bad nymph for quick jigs vex. Glib jocks quiz nymph to vex dwarf. How quickly daft jumping zebras vex.',
  'The lazy dog slept under the warm sun. Birds fly south for the winter season. She read the book in one sitting. The old man walked slowly down the street. Children play in the park every afternoon. Coffee tastes better in the morning. Music fills the room with joy. Rain fell softly on the roof. The cat curled up by the fire. Stars twinkle in the night sky.',
  'Time flies when you are having fun. Learning new skills takes practice and patience. The river flows gently through the valley. Books open doors to new worlds. Friends make life more enjoyable. Nature has a way of healing the soul. Every day brings new opportunities. Kindness costs nothing but means everything. The best things in life are free. Hard work always pays off in the end.',
  'A smile can brighten someone else\'s day. Change is the only constant in life. Dreams give us something to strive for. Patience is a virtue worth cultivating. The early bird catches the worm. Actions speak louder than words. Practice makes perfect over time. Life is what you make of it. Every cloud has a silver lining. The journey of a thousand miles begins with a single step.',
  'In the heart of the city, people rush from one place to another without stopping to look around. The streets are filled with the sound of traffic and the chatter of crowds. Sometimes we forget to appreciate the small moments that make life meaningful. A kind word or a helping hand can change someone\'s entire day. We should never underestimate the power of simple gestures.',
  'The mountains stood tall against the blue sky, their peaks covered in snow. Hikers from all over the world came to experience the breathtaking views. Each step brought them closer to the summit and to their personal goals. The journey was difficult but the sense of accomplishment was worth every effort. Nature has a way of putting things into perspective.',
  'Technology has transformed the way we communicate and work. We can now connect with people across the globe in an instant. However, it is important to remember the value of face to face conversation. Balance between the digital world and the real world is essential. We must use technology wisely and not let it control our lives.',
  'Cooking a meal from scratch can be one of the most rewarding experiences. The smell of fresh ingredients and the sizzle of the pan create a sense of warmth. Sharing food with loved ones strengthens bonds and creates lasting memories. Every culture has its own unique recipes passed down through generations. There is something special about a home cooked dinner.',
  'Reading opens the door to countless worlds and ideas. Whether it is fiction or non fiction, books have the power to inspire. They allow us to see life through different perspectives and understand others better. A good book can be a friend during lonely times. We should never stop learning and exploring through the written word.',
  'The ocean stretches as far as the eye can see, its waves crashing against the shore. Sailors have ventured into these waters for centuries in search of adventure. The sea holds many secrets and stories that have yet to be told. It reminds us of both the beauty and the power of nature. We must protect our oceans for future generations.',
  'Music has the ability to evoke emotions that words alone cannot express. A single melody can transport us back to a specific moment in time. Musicians spend years perfecting their craft and sharing their passion with the world. Whether you play an instrument or simply listen, music connects us all. It is a universal language that transcends borders.',
  'Morning routines set the tone for the rest of the day. Some people prefer to start with exercise while others enjoy a quiet cup of coffee. Taking a few moments to plan ahead can make a significant difference. A healthy breakfast provides the energy needed to tackle challenges. How we begin our day often determines how we feel when it ends.',
  'Travel broadens the mind and creates memories that last a lifetime. Experiencing new cultures and customs helps us grow as individuals. We learn that despite our differences, people everywhere share similar hopes and dreams. Stepping outside our comfort zone can lead to unexpected discoveries. The world has so much to offer to those willing to explore.',
  'Gardening teaches patience and the importance of nurturing growth. Watching a seed transform into a plant is a small miracle. The connection to the earth and the rhythm of the seasons brings peace. Even in a small space, we can create something beautiful and productive. Tending to plants is a gentle reminder to tend to ourselves as well.',
] as const

export function getRandomSentence(): string {
  const idx = Math.floor(Math.random() * SENTENCES.length)
  return SENTENCES[idx]
}
